#!/bin/bash

# WORKSPACES 
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# CONFIGS
bspc config border_width         1
bspc config window_gap          18
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#282828"
bspc config focused_border_color "#b8bb26"
bspc config presel_feedback_color"#b8bb26"

# RULES
bspc rule -a LibreWolf desktop='^1'
bspc rule -a mpv desktop='^6' state=floating
bspc rule -a transmission desktop='^8'
bspc rule -a KeePassXC desktop='^3'
bspc rule -a Thunar desktop='^4'

# AUTOSTART
sxhkd &
$HOME/.config/polybar/launch.sh &
nitrogen --restore &
conky
